### ISSUE TITLE
Scrip de generacion de esquemas de la base de datos

### ISSUE THREAD

**Issue by kevinserrano01** [kevinserrano01/SUPERMARK-Java#3]
#Proyecto SuperMark

Necesito las tablas de proyecto siguiendo la narrativa, ojo con las consideraciones.
@TomiiPorrini  vos te encargas de eso y punto. Mboeeee

**Comment by TomiiPorrini** [comment]
Eh gato, ese era tu trabajo. yo me encargaba del resto :c @kevinserrano01
