### ISSUE TITLE
DER  Supermark

### ISSUE THREAD

**Issue by TomiiPorrini** [kevinserrano01/SUPERMARK-Java#8]
@enzzo19 Profe, aqui se lo dejo. recien pude exportarlo, no sabia como hacerlo jajaja
![DER-GRUPO11 drawio](https://user-images.githubusercontent.com/105433665/174848517-3460523d-91c5-4eb4-9af3-31823a32e914.png)

**Comment by kevinserrano01** [comment]
Muy bueno tomi, Si el profe da el okey, porias subirlo al main creando una carpeta nueva que contenga ese DER.
